# Generated by Django 5.2.7 on 2025-10-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='estoque/anexos/'),
        ),
    ]
